### ISSUE TITLE
FIX ME!!!!!!

### ISSUE THREAD

**Issue by leand12** [MarioCSilva/Orcamento#3]
Greetings, that's a cool little project u got there. But u forgot to make usability tests to find these sad errors that could be avoided.

1. When a negative value is inserted, things don't go very well:

![image](https://user-images.githubusercontent.com/60890792/182403498-9880c215-a79c-4dbd-a9d4-a770ab323c62.png)
![image](https://user-images.githubusercontent.com/60890792/182403539-266b2606-a85a-4634-a3ae-6163fac8a4c7.png)

2. Cards are white despite dark mode enabled

3. Hmmm...

![image](https://user-images.githubusercontent.com/60890792/182403749-d6be3a2a-1bc2-464e-b253-538b9102d49f.png)

I advise u to fix this quickly, since it does not look well on the UX.

BR, Leandro Silva, Co-Founder of Chubix

**Comment by MarioCSilva** [comment]
Thanks for the suggestions, will work on it soon

**Comment by MarioCSilva** [comment]
A new fix has been committed
